### ISSUE TITLE
Exporting linked duplicates creates multiple elements with the same id

### ISSUE THREAD

**Issue by simpae** [ksons/xml3d-blender-exporter#9]
Using ````Duplicate Linked (Alt D)```` to create multiple instances of the same mesh results in multiple ````<model>```` elements with the same ````id```` (the name of the mesh the object is linked to).

Reproduce:
* Duplicate an existing object using the ````Duplicate Linked (Alt D)```` command in Blender
* Export

**Comment by ksons** [comment]
Confirmed. Exporter is using the (possible shared) name of the data block.

I'd suggest to omit ids for the ``<model>`` element because they just point to possibly shared assets (there is no 1:1 mapping to a single blender entity).

Opinions?

**Comment by simpae** [comment]
Since the parent ````<group>```` already has the objects (unique) Blender name as its ````id````, I agree with your opinion.
Selecting the ````<model>```` directly could still be done using ````#groupId > model```` or similar.
